# Generated by Django 5.0 on 2024-09-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empolyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Tilename', models.CharField(max_length=30)),
                ('HasPassport', models.BooleanField()),
                ('Salary', models.IntegerField()),
                ('DOB', models.DateField()),
                ('HireDate', models.DateField()),
                ('Notes', models.CharField(max_length=200)),
                ('Country', models.CharField(choices=[('IND', 'India'), ('AUS', 'Australia'), ('UK', 'United Kingdome'), ('USA', 'United States of America'), ('JPN', 'Japan')], default=None, max_length=35)),
            ],
        ),
    ]
