# Generated by Django 5.0 on 2024-09-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empolyee',
            name='Email',
            field=models.EmailField(default=None, max_length=50),
        ),
    ]
