# Generated by Django 5.0 on 2024-09-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayRollApp', '0004_remove_empolyee_country_empolyee_empcountry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTimeEmpolyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Tilename', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empolyee',
            name='EmpCountry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.country'),
        ),
        migrations.AlterField(
            model_name='empolyee',
            name='EmpDeparment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='PayRollApp.department'),
        ),
    ]
